name: publish-to-pypi-and-test-pypi

on:
  push:
    tags:
      - v*

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        type: string
      skip_pypi:
        description: 'Skip PyPI publication'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: build-dist 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      publish-to-pypi 📢
    if: ${{startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '.dev') && !inputs.skip_pypi }}  # only publish to PyPI on tag pushes and skip if manually triggered
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/decombinator
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: download-dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: publish-dist-to-pypi 
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: >-
      signed-github-release ✍️
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore
    steps:
    - name: download-dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: sign-with-sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ inputs.tag || github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ inputs.tag || github.ref_name }}' dist/**
        --repo '${{ github.repository }}'

  publish-to-testpypi:
    name: publish-to-testpypi 🔨
    if: ${{startsWith(github.ref, 'refs/tags/') && contains(github.ref, '.dev')}}  # only publish to test-PyPI on dev tag pushes
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: test-pypi
      url: https://test.pypi.org/p/decombinator

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: download-dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: publish-dist-to-testpypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
